# Generated by Django 3.2.14 on 2022-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=50, verbose_name='Unique_ID')),
                ('step', models.IntegerField(verbose_name='Step')),
                ('pain', models.IntegerField(verbose_name='Pain')),
            ],
            options={
                'verbose_name': 'Session',
            },
        ),
    ]
