# Generated by Django 4.0.5 on 2022-07-14 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.CharField(default=django.utils.timezone.now, max_length=20, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
