# Generated by Django 4.0.5 on 2022-07-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_session_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='distance',
            field=models.IntegerField(default=0, verbose_name='Distance'),
            preserve_default=False,
        ),
    ]
