# Generated by Django 4.0.5 on 2022-07-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_session_end_session_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='distance',
            field=models.FloatField(verbose_name='Distance'),
        ),
    ]
